### ISSUE TITLE
This project is alive?

### ISSUE THREAD

**Issue by Classsic** [qwertangel/darkflow-docker#3]
Hi, somebody is keeping update this image? If the answer is yes, I want to know how detect object from rtsp stream.
When run detect.py, i get this error:
`/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "detect.py", line 2, in <module>
    from darkflow.net.build import TFNet
  File "/darkflow/darkflow/net/build.py", line 7, in <module>
    from .framework import create_framework
  File "/darkflow/darkflow/net/framework.py", line 1, in <module>
    from . import yolo
  File "/darkflow/darkflow/net/yolo/__init__.py", line 2, in <module>
    from . import predict
  File "/darkflow/darkflow/net/yolo/predict.py", line 7, in <module>
    from ...cython_utils.cy_yolo_findboxes import yolo_box_constructor
ImportError: No module named cy_yolo_findboxes`
Please pointme the steps to follow, or any docs to read.
Thanks.

**Comment by carefulcomputer** [comment]
sorry.. haven't worked on it a while. BTW first issue is just a warning "Conversion of the second argument of issubdtype from floattonp.floatingis deprecated. In future, it will be treated asnp.float64 == np.dtype(float).type. from ._conv import register_converters as _register_converters Traceback (most recent call last)" . However yolo might have been updated and broken build. "No module named cy_yolo_findboxes" . You can try looking at changes related to cython in yolo to fix it.
